### ISSUE TITLE
Shapely Parallax widget cause error when using Elementor Plugin

### ISSUE THREAD

**Issue by laranz** [puikinsh/shapely#223] opened 2017-09-06 21:41 UTC
Shapely parallax widget don't show images when using Elementor plugin https://wordpress.org/plugins/elementor/

Reported here: https://colorlib.com/wp/forums/topic/parallax-widget-doesnt-show-photographs/

**Comment by cristianraiber** [comment] 2017-10-09 07:43
This is most likely a plugin incompatibility issue. I'm suspecting both the theme and Elementor are using the same JS script to generate that parallax effect, but we'll investigate.

**Comment by giucu91** [comment] 2017-10-19 07:50
Hello @laranz ,

I installed the last version of Elementor and everything is ok at my end. Can you check to see if it's working now ?

Thank you,
George.

**Comment by giucu91** [comment] 2017-10-20 06:51
Thank you @laranz .

**Comment by kingly17** [comment] 2018-01-10 11:07
@giucu91 and @laranz ,

Good morning and I hope this meets you well.

I am having the EXACT same issue as reported by carolines on the Shapely support forum.

The Background Image on my website does not display when set to Background Full.

But when I deactivate the Elementor plugin, viola!, it displays correctly.

The issue is that I need the Elementor plugin on my website because I have other pages that use it.

Can you help me PLEASE!!!!

Much appreciated.

**Comment by hubyhuby** [comment] 2018-02-08 16:23
I have the same kind of issue with the paralax sections, when I try to insert it on a PAGE.
I installed a shortcode plugin to be able to have widget in pages but then , No images in paralax backgrounds.

**Comment by cristianraiber** [comment] 2018-04-20 20:05
@hubyhuby - this is actually a duplicate of #257 
@kingly17 - I tried reproducing your error to no avail :/ It's been working fine for me

**Closed by cristianraiber** 2018-04-20 20:05 UTC
Labels: bug
