### ISSUE TITLE
X-Post from Companion: Error upon activating Shapely Companion Plugin

### ISSUE THREAD

**Issue by kupoback** [puikinsh/shapely#146] opened 2017-01-19 21:01 UTC
After installing the Shapely Theme, I started installing the recommended plugins, one being Shapely Companion. [Reference support ticket](https://colorlib.com/wp/forums/topic/issue-installing-shapely-companion/#post-84844)

Upon activating the plugin, I receive this error:

    Parse error: syntax error, unexpected '[' in /nas/content/staging/domain/wp-content/plugins/shapely-companion/inc/widgets/widget-home-clients.php on line 84

Any idea what the issue could be? I am running Theme beta, per Support suggestion, and WordPress 4.7.1

**Comment by cristianraiber** [comment] 2017-01-19 22:19
Duplicate of: https://github.com/puikinsh/shapely-companion/issues/4

**Closed by cristianraiber** 2017-01-19 22:19 UTC
Labels: duplicate
