### ISSUE TITLE
In the customizer parallax background images don't display due to javascript error message

### ISSUE THREAD

**Issue by FreeWPTP** [puikinsh/shapely#91] opened 2016-12-06 12:40 UTC
Related Topic :

https://colorlib.com/wp/forums/topic/incorrect-display-of-buttons-on-parallax-background-and-photo-mode-customize/#post-80294

**Comment by cristianraiber** [comment] 2016-12-09 10:11
Duplicate of: #45

**Closed by cristianraiber** 2016-12-09 10:11 UTC
Labels: duplicate
