### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by dawidrylko** [puikinsh/shapely#8] opened 2016-04-05 18:55 UTC
Parse error in this theme:
`Parse error: syntax error, unexpected '[' in */wp-content/themes/shapely/inc/widgets/widget-home-clients.php on line 18`

Regards,
Rylko

**Comment by puikinsh** [comment] 2016-04-06 08:15
@dawidrylko 

What version of PHP do you use? 

Some users are reporting this error but it is not present on PHP7

**Comment by dawidrylko** [comment] 2016-04-06 17:15
@puikinsh 

That's right! On PHP 7.0 the problem doesn't occur. I use PHP 5.5.

**Comment by FreeWPTP** [comment] 2016-04-07 06:27
Related Topic :

https://colorlib.com/wp/forums/topic/error-after-activate/

**Comment by FreeWPTP** [comment] 2016-04-15 09:35
Some users can't update PHP version on the server so the issue should be fixed in the theme.  Related https://colorlib.com/wp/forums/topic/theme-admin-page-gone/#post-52005

**Comment by puikinsh** [comment] 2016-04-15 15:29
Since error doesn't appear for me even on PHP 5.5 it would be nice if someone could test the latest theme version (1.0.2).

**Comment by dawidrylko** [comment] 2016-04-15 16:43
@puikinsh

Version 1.0.2 is stable on PHP 5.4, PHP 5.5, PHP 5.6 and PHP 7. Unfortunately parse error exist on PHP 5.3 and PHP 5.2.

You can close this issue.

Regards,
Rylko

**Comment by puikinsh** [comment] 2016-04-15 16:50
Thank you for notifying!

**Closed by puikinsh** 2016-04-15 16:50 UTC

**Comment by FreeWPTP** [comment] 2016-04-20 14:08
Another Topic :

https://colorlib.com/wp/forums/topic/shapely-syntax-error/

**Comment by puikinsh** [comment] 2016-04-20 16:18
@FreeWPTP

That thread is dated back to date before it was already fixed.

**Comment by FreeWPTP** [comment] 2016-04-21 06:17
Sorry i didn't see it that the issue is fixed in this commit https://github.com/puikinsh/shapely/commit/386de1243988af58a10545bf0c3a9be8eaca4d36 6 days ago and the topic is also created around that time.
