### ISSUE TITLE
Search Bar Gitters

### ISSUE THREAD

**Issue by a-support** [puikinsh/shapely#238] opened 2017-11-12 14:50 UTC
Hey there,
When you hover over the search bar and move the pointer a bit over the search bar it starts to disappear. 
Screencast: http://recordit.co/jMHpkntrUF

https://colorlib.com/wp/forums/topic/search-bag-bugged/#post-131568

**Comment by hubyhuby** [comment] 2017-11-28 17:27
I confirme the same behaviour on my installation of shapely 1.2

**Comment by cristianraiber** [comment] 2018-04-20 20:10
@hubyhuby @a-support - I'll get this fixed in v1.2.2

**Comment by cristianraiber** [comment] 2018-04-23 14:54
@hubyhuby @a-support - there was a small issue with this, indeed. The padding set for the search icon was a bit too big and that made it show the search bar even when not hovered exactly over the search icon.

However, the search bar is supposed to start disappearing once you hover outside of it's "active" area. What you're currently seeing is actual normal & expected behaviour. The Search bar displays `only` when hovered over the search icon.

**Comment by cristianraiber** [comment] 2018-04-23 14:56
This is not a bug.

**Closed by cristianraiber** 2018-04-23 14:56 UTC
Labels: invalid
